import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import connectDatabase from './config/database';
import Workout from './models/Workout';
import Diet from './models/Diet';

// Sample workout data for each day of the week at different difficulty levels
const sampleWorkouts = [
  // Monday - Chest & Triceps
  {
    name: 'Chest & Triceps Power',
    description: 'Build a powerful chest and defined triceps with this compound movement-focused workout.',
    day: 'Monday',
    difficulty: 'intermediate',
    duration: 60,
    caloriesBurned: 450,
    muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
    category: 'strength',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
    isPublic: true,
    likes: 245,
    exercises: [
      {
        name: 'Barbell Bench Press',
        description: 'The king of chest exercises for building mass and strength.',
        sets: 4,
        reps: '8-10',
        restTime: '90 seconds',
        muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
        equipment: 'Barbell, Bench',
        difficulty: 'intermediate',
        instructions: [
          'Lie flat on the bench with feet firmly on the ground',
          'Grip the barbell slightly wider than shoulder-width',
          'Lower the bar to your chest in a controlled manner',
          'Push the bar back up explosively to starting position',
        ],
      },
      {
        name: 'Incline Dumbbell Press',
        description: 'Targets the upper chest for full chest development.',
        sets: 3,
        reps: '10-12',
        restTime: '75 seconds',
        muscleGroups: ['Upper Chest', 'Shoulders'],
        equipment: 'Dumbbells, Incline Bench',
        difficulty: 'intermediate',
        instructions: [
          'Set bench to 30-45 degree incline',
          'Hold dumbbells at chest level with palms facing forward',
          'Press dumbbells up and slightly inward',
          'Lower slowly and repeat',
        ],
      },
      {
        name: 'Cable Flyes',
        description: 'Isolation exercise for chest definition and stretch.',
        sets: 3,
        reps: '12-15',
        restTime: '60 seconds',
        muscleGroups: ['Chest'],
        equipment: 'Cable Machine',
        difficulty: 'intermediate',
        instructions: [
          'Stand in center of cable machine',
          'Hold cable handles at shoulder height',
          'Bring hands together in front of chest',
          'Slowly open arms and repeat',
        ],
      },
      {
        name: 'Tricep Pushdowns',
        description: 'Effective isolation exercise for tricep development.',
        sets: 3,
        reps: '12-15',
        restTime: '60 seconds',
        muscleGroups: ['Triceps'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: [
          'Stand facing cable machine',
          'Hold bar at chest height with overhand grip',
          'Push bar down until arms are fully extended',
          'Slowly return to starting position',
        ],
      },
      {
        name: 'Skull Crushers',
        description: 'Build tricep mass and strength with this classic exercise.',
        sets: 3,
        reps: '10-12',
        restTime: '75 seconds',
        muscleGroups: ['Triceps'],
        equipment: 'EZ Bar, Bench',
        difficulty: 'intermediate',
        instructions: [
          'Lie on bench holding EZ bar above chest',
          'Lower bar toward forehead by bending at elbows',
          'Extend arms back to starting position',
          'Keep upper arms stationary throughout',
        ],
      },
    ],
  },
  // Tuesday - Back & Biceps
  {
    name: 'Back & Biceps Strength',
    description: 'Build a wide, thick back and powerful biceps with these essential pulling movements.',
    day: 'Tuesday',
    difficulty: 'intermediate',
    duration: 65,
    caloriesBurned: 480,
    muscleGroups: ['Back', 'Biceps', 'Rear Deltoids'],
    category: 'strength',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
    isPublic: true,
    likes: 312,
    exercises: [
      {
        name: 'Deadlifts',
        description: 'The ultimate compound movement for total back and posterior chain development.',
        sets: 4,
        reps: '5-6',
        restTime: '3 minutes',
        muscleGroups: ['Lower Back', 'Glutes', 'Hamstrings', 'Traps'],
        equipment: 'Barbell',
        difficulty: 'advanced',
        instructions: [
          'Stand with feet hip-width apart, bar over mid-foot',
          'Hinge at hips and grip bar just outside legs',
          'Brace core and lift by pushing floor away',
          'Lock out hips at top, then lower with control',
        ],
      },
      {
        name: 'Pull-Ups',
        description: 'Best bodyweight exercise for building lat width.',
        sets: 4,
        reps: '8-12',
        restTime: '90 seconds',
        muscleGroups: ['Lats', 'Biceps', 'Rear Deltoids'],
        equipment: 'Pull-up Bar',
        difficulty: 'intermediate',
        instructions: [
          'Hang from bar with overhand grip, wider than shoulders',
          'Pull yourself up until chin clears the bar',
          'Lower slowly with control',
          'Avoid swinging or kipping',
        ],
      },
      {
        name: 'Barbell Rows',
        description: 'Build back thickness and strength with this essential compound exercise.',
        sets: 4,
        reps: '8-10',
        restTime: '90 seconds',
        muscleGroups: ['Middle Back', 'Lats', 'Biceps'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: [
          'Hinge forward at hips, back straight, bar in hands',
          'Pull bar to lower chest/upper abdomen',
          'Squeeze shoulder blades at top',
          'Lower bar under control',
        ],
      },
      {
        name: 'Barbell Curls',
        description: 'Classic bicep builder for size and strength.',
        sets: 3,
        reps: '10-12',
        restTime: '75 seconds',
        muscleGroups: ['Biceps'],
        equipment: 'Barbell',
        difficulty: 'beginner',
        instructions: [
          'Stand with barbell at hip level, underhand grip',
          'Curl bar up to shoulder height',
          'Squeeze biceps at top',
          'Lower slowly to starting position',
        ],
      },
    ],
  },
  // Wednesday - Legs
  {
    name: 'Leg Day Domination',
    description: 'Never skip leg day! This comprehensive lower body workout builds strength and mass.',
    day: 'Wednesday',
    difficulty: 'intermediate',
    duration: 70,
    caloriesBurned: 550,
    muscleGroups: ['Quadriceps', 'Hamstrings', 'Glutes', 'Calves'],
    category: 'strength',
    imageUrl: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=500',
    isPublic: true,
    likes: 289,
    exercises: [
      {
        name: 'Barbell Squats',
        description: 'The king of all exercises. Builds leg strength, mass, and athletic power.',
        sets: 5,
        reps: '5-8',
        restTime: '3 minutes',
        muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
        equipment: 'Barbell, Squat Rack',
        difficulty: 'intermediate',
        instructions: [
          'Position bar on upper traps, feet shoulder-width apart',
          'Brace core and descend until thighs are parallel to floor',
          'Drive through heels to stand back up',
          'Keep knees tracking over toes throughout',
        ],
      },
      {
        name: 'Romanian Deadlifts',
        description: 'Excellent hamstring and glute builder with hip hinge movement.',
        sets: 4,
        reps: '10-12',
        restTime: '90 seconds',
        muscleGroups: ['Hamstrings', 'Glutes', 'Lower Back'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: [
          'Stand with barbell at hip level',
          'Push hips back while lowering bar along legs',
          'Feel stretch in hamstrings, then drive hips forward',
          'Keep back straight throughout movement',
        ],
      },
      {
        name: 'Leg Press',
        description: 'Machine-based quad and glute exercise for additional volume.',
        sets: 4,
        reps: '12-15',
        restTime: '75 seconds',
        muscleGroups: ['Quadriceps', 'Glutes'],
        equipment: 'Leg Press Machine',
        difficulty: 'beginner',
        instructions: [
          'Sit in leg press machine with feet on platform',
          'Lower weight until knees are at 90 degrees',
          'Push through heels to extend legs',
          'Do not lock out knees at top',
        ],
      },
      {
        name: 'Calf Raises',
        description: 'Develops the gastrocnemius and soleus for complete leg development.',
        sets: 4,
        reps: '15-20',
        restTime: '60 seconds',
        muscleGroups: ['Calves'],
        equipment: 'Calf Raise Machine or Barbell',
        difficulty: 'beginner',
        instructions: [
          'Stand on edge of platform with heels hanging',
          'Rise onto toes as high as possible',
          'Hold briefly at top',
          'Lower heels below platform for full stretch',
        ],
      },
    ],
  },
  // Thursday - Shoulders & Abs
  {
    name: 'Shoulders & Core Circuit',
    description: 'Build boulder shoulders and a rock-solid core with this targeted workout.',
    day: 'Thursday',
    difficulty: 'intermediate',
    duration: 55,
    caloriesBurned: 400,
    muscleGroups: ['Shoulders', 'Core', 'Traps'],
    category: 'strength',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500',
    isPublic: true,
    likes: 198,
    exercises: [
      {
        name: 'Overhead Press',
        description: 'The fundamental shoulder strength builder.',
        sets: 4,
        reps: '6-8',
        restTime: '2 minutes',
        muscleGroups: ['Shoulders', 'Triceps', 'Core'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: [
          'Hold barbell at shoulder height, clean grip',
          'Press bar directly overhead',
          'Lock out arms at top',
          'Lower bar to shoulders with control',
        ],
      },
      {
        name: 'Lateral Raises',
        description: 'Develops the medial deltoid for shoulder width.',
        sets: 4,
        reps: '12-15',
        restTime: '60 seconds',
        muscleGroups: ['Side Deltoids'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: [
          'Stand with dumbbells at sides',
          'Raise arms out to sides until parallel to floor',
          'Lead with elbows, not hands',
          'Lower slowly back to sides',
        ],
      },
      {
        name: 'Face Pulls',
        description: 'Excellent rear delt and rotator cuff exercise.',
        sets: 3,
        reps: '15-20',
        restTime: '60 seconds',
        muscleGroups: ['Rear Deltoids', 'Rotator Cuff'],
        equipment: 'Cable Machine, Rope',
        difficulty: 'beginner',
        instructions: [
          'Set cable at face height with rope attachment',
          'Pull rope toward face, separating hands at end',
          'Focus on rear delt contraction',
          'Slowly return to starting position',
        ],
      },
      {
        name: 'Plank',
        description: 'Core stabilization exercise for functional strength.',
        sets: 3,
        reps: '60 seconds',
        restTime: '45 seconds',
        muscleGroups: ['Core', 'Shoulders', 'Glutes'],
        difficulty: 'beginner',
        instructions: [
          'Get into push-up position, rest on forearms',
          'Keep body in straight line from head to heels',
          'Brace core and squeeze glutes',
          'Hold for prescribed time',
        ],
      },
    ],
  },
  // Friday - Full Body HIIT
  {
    name: 'Full Body HIIT Blast',
    description: 'High-intensity interval training for maximum calorie burn and conditioning.',
    day: 'Friday',
    difficulty: 'advanced',
    duration: 45,
    caloriesBurned: 600,
    muscleGroups: ['Full Body'],
    category: 'hiit',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500',
    isPublic: true,
    likes: 445,
    exercises: [
      {
        name: 'Burpees',
        description: 'Full body explosive exercise for maximum calorie burn.',
        sets: 5,
        reps: '10',
        restTime: '30 seconds',
        muscleGroups: ['Full Body'],
        difficulty: 'advanced',
        instructions: [
          'Start standing, drop to squat position',
          'Jump feet back to push-up position',
          'Perform push-up, then jump feet to hands',
          'Explode up into jump with arms overhead',
        ],
      },
      {
        name: 'Jump Squats',
        description: 'Explosive lower body exercise for power and conditioning.',
        sets: 4,
        reps: '15',
        restTime: '30 seconds',
        muscleGroups: ['Quadriceps', 'Glutes', 'Calves'],
        difficulty: 'intermediate',
        instructions: [
          'Stand with feet shoulder-width apart',
          'Perform squat then explode into jump',
          'Land softly with bent knees',
          'Immediately go into next squat',
        ],
      },
      {
        name: 'Mountain Climbers',
        description: 'Dynamic core exercise that elevates heart rate.',
        sets: 4,
        reps: '30 seconds',
        restTime: '20 seconds',
        muscleGroups: ['Core', 'Shoulders', 'Hip Flexors'],
        difficulty: 'intermediate',
        instructions: [
          'Start in high push-up position',
          'Drive right knee toward chest',
          'Quickly switch legs in running motion',
          'Keep hips level, move rapidly',
        ],
      },
      {
        name: 'Box Jumps',
        description: 'Plyometric exercise for explosive power.',
        sets: 4,
        reps: '8-10',
        restTime: '45 seconds',
        muscleGroups: ['Quadriceps', 'Glutes', 'Calves'],
        equipment: 'Plyo Box',
        difficulty: 'advanced',
        instructions: [
          'Stand facing box, feet shoulder-width apart',
          'Swing arms and bend knees to load',
          'Explode up onto box',
          'Step back down carefully, do not jump down',
        ],
      },
    ],
  },
  // Saturday - Active Recovery (Yoga/Flexibility)
  {
    name: 'Yoga & Flexibility Flow',
    description: 'Improve flexibility, mobility, and recovery with this relaxing yoga-inspired session.',
    day: 'Saturday',
    difficulty: 'beginner',
    duration: 45,
    caloriesBurned: 200,
    muscleGroups: ['Full Body', 'Core'],
    category: 'yoga',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500',
    isPublic: true,
    likes: 178,
    exercises: [
      {
        name: 'Sun Salutation',
        description: 'A flowing sequence to warm up the entire body.',
        sets: 3,
        reps: '5 rounds',
        restTime: '30 seconds',
        muscleGroups: ['Full Body'],
        difficulty: 'beginner',
        instructions: [
          'Start in mountain pose, inhale arms up',
          'Forward fold, then step back to plank',
          'Lower to low push-up, upward facing dog',
          'Downward facing dog, step forward, rise up',
        ],
      },
      {
        name: 'Pigeon Pose',
        description: 'Deep hip opener for improved flexibility.',
        sets: 2,
        reps: '60 seconds each side',
        restTime: '30 seconds',
        muscleGroups: ['Hip Flexors', 'Glutes', 'IT Band'],
        difficulty: 'beginner',
        instructions: [
          'From downward dog, bring right knee to right wrist',
          'Extend left leg straight back',
          'Lower hips toward floor',
          'Hold for breath cycles, then switch sides',
        ],
      },
      {
        name: 'Seated Spinal Twist',
        description: 'Releases tension in the spine and improves rotational mobility.',
        sets: 2,
        reps: '60 seconds each side',
        restTime: '20 seconds',
        muscleGroups: ['Spine', 'Core', 'Hips'],
        difficulty: 'beginner',
        instructions: [
          'Sit with legs extended, cross right foot over left knee',
          'Place right hand behind you, left elbow on right knee',
          'Twist to the right on each exhale',
          'Hold and breathe, then switch sides',
        ],
      },
    ],
  },
  // Sunday - Rest or Light Cardio
  {
    name: 'Light Cardio & Core',
    description: 'Active recovery with light cardio and core work to end the week strong.',
    day: 'Sunday',
    difficulty: 'beginner',
    duration: 40,
    caloriesBurned: 300,
    muscleGroups: ['Core', 'Cardiovascular'],
    category: 'cardio',
    imageUrl: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=500',
    isPublic: true,
    likes: 134,
    exercises: [
      {
        name: 'Light Jog / Walk',
        description: 'Easy cardiovascular activity to promote blood flow and recovery.',
        sets: 1,
        reps: '20 minutes',
        restTime: '0',
        muscleGroups: ['Cardiovascular', 'Legs'],
        difficulty: 'beginner',
        instructions: [
          'Start with 5 minute walk to warm up',
          'Transition to light jog at comfortable pace',
          'Maintain conversational pace throughout',
          'Cool down with 5 minute walk',
        ],
      },
      {
        name: 'Bicycle Crunches',
        description: 'Effective abdominal exercise targeting all core muscles.',
        sets: 3,
        reps: '20',
        restTime: '45 seconds',
        muscleGroups: ['Abdominals', 'Obliques'],
        difficulty: 'beginner',
        instructions: [
          'Lie on back, hands behind head, legs raised',
          'Bring right elbow to left knee',
          'Simultaneously extend right leg',
          'Alternate sides in pedaling motion',
        ],
      },
      {
        name: 'Dead Bug',
        description: 'Anti-extension core exercise for stability.',
        sets: 3,
        reps: '10 each side',
        restTime: '45 seconds',
        muscleGroups: ['Core', 'Hip Flexors'],
        difficulty: 'beginner',
        instructions: [
          'Lie on back, arms extended to ceiling, knees at 90 degrees',
          'Lower right arm and left leg toward floor',
          'Keep lower back pressed to floor',
          'Return to start and switch sides',
        ],
      },
    ],
  },
  // Beginner versions
  {
    name: 'Beginner Upper Body',
    description: 'Perfect introduction to upper body training for beginners.',
    day: 'Monday',
    difficulty: 'beginner',
    duration: 40,
    caloriesBurned: 250,
    muscleGroups: ['Chest', 'Shoulders', 'Arms'],
    category: 'strength',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
    isPublic: true,
    likes: 167,
    exercises: [
      {
        name: 'Push-Ups',
        description: 'Classic upper body exercise requiring no equipment.',
        sets: 3,
        reps: '8-12',
        restTime: '90 seconds',
        muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
        difficulty: 'beginner',
        instructions: [
          'Place hands slightly wider than shoulders',
          'Keep body in straight line from head to heels',
          'Lower chest to floor',
          'Push up to starting position',
        ],
      },
      {
        name: 'Dumbbell Shoulder Press',
        description: 'Beginner-friendly shoulder exercise with dumbbells.',
        sets: 3,
        reps: '10-12',
        restTime: '75 seconds',
        muscleGroups: ['Shoulders', 'Triceps'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: [
          'Sit upright with dumbbells at shoulder height',
          'Press dumbbells overhead',
          'Fully extend arms at top',
          'Lower to shoulder height and repeat',
        ],
      },
      {
        name: 'Dumbbell Bicep Curls',
        description: 'Basic bicep exercise for beginners.',
        sets: 3,
        reps: '12-15',
        restTime: '60 seconds',
        muscleGroups: ['Biceps'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: [
          'Stand with dumbbells at sides',
          'Curl both dumbbells to shoulder height',
          'Squeeze biceps at top',
          'Lower slowly and repeat',
        ],
      },
    ],
  },
];

// Sample diet plans
const sampleDiets = [
  // Weight Loss Plan
  {
    name: 'Fat Shredding Diet Plan',
    description: 'A strategic calorie deficit plan designed to maximize fat loss while preserving lean muscle mass.',
    goal: 'weight_loss',
    dailyCalories: 1800,
    macros: { protein: 35, carbs: 35, fats: 30 },
    tags: ['fat loss', 'lean', 'high protein', 'low carb'],
    difficulty: 'moderate',
    duration: 12,
    isPublic: true,
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=500',
    meals: [
      {
        name: 'Breakfast',
        time: '7:00 AM',
        totalCalories: 400,
        totalProtein: 35,
        totalCarbs: 30,
        totalFats: 10,
        foods: [
          { name: 'Greek Yogurt', amount: '200g', calories: 130, protein: 17, carbs: 8, fats: 2, recipe: 'Choose plain, low-fat Greek yogurt for maximum protein.' },
          { name: 'Mixed Berries', amount: '100g', calories: 50, protein: 1, carbs: 12, fats: 0 },
          { name: 'Whole Grain Toast', amount: '1 slice (30g)', calories: 80, protein: 3, carbs: 15, fats: 1 },
          { name: 'Egg Whites', amount: '3 whites (90g)', calories: 52, protein: 11, carbs: 1, fats: 0, recipe: 'Scramble with vegetables for a complete breakfast.' },
          { name: 'Black Coffee', amount: '1 cup (240ml)', calories: 5, protein: 0, carbs: 1, fats: 0 },
        ],
      },
      {
        name: 'Mid-Morning Snack',
        time: '10:00 AM',
        totalCalories: 200,
        totalProtein: 20,
        totalCarbs: 15,
        totalFats: 5,
        foods: [
          { name: 'Protein Shake', amount: '1 scoop (30g)', calories: 120, protein: 25, carbs: 3, fats: 2 },
          { name: 'Apple', amount: '1 medium (182g)', calories: 95, protein: 0, carbs: 25, fats: 0 },
        ],
      },
      {
        name: 'Lunch',
        time: '1:00 PM',
        totalCalories: 550,
        totalProtein: 45,
        totalCarbs: 50,
        totalFats: 15,
        foods: [
          { name: 'Grilled Chicken Breast', amount: '180g', calories: 280, protein: 53, carbs: 0, fats: 6, recipe: 'Season with herbs, garlic, and lemon. Grill until internal temp reaches 165°F.' },
          { name: 'Brown Rice', amount: '150g cooked', calories: 165, protein: 4, carbs: 35, fats: 1 },
          { name: 'Steamed Broccoli', amount: '200g', calories: 70, protein: 6, carbs: 14, fats: 1 },
          { name: 'Olive Oil', amount: '1 tsp (5ml)', calories: 40, protein: 0, carbs: 0, fats: 5 },
        ],
      },
      {
        name: 'Afternoon Snack',
        time: '4:00 PM',
        totalCalories: 150,
        totalProtein: 12,
        totalCarbs: 10,
        totalFats: 7,
        foods: [
          { name: 'Almonds', amount: '20g (about 20 almonds)', calories: 116, protein: 4, carbs: 4, fats: 10 },
          { name: 'Cherry Tomatoes', amount: '100g', calories: 35, protein: 2, carbs: 8, fats: 0 },
        ],
      },
      {
        name: 'Dinner',
        time: '7:00 PM',
        totalCalories: 500,
        totalProtein: 40,
        totalCarbs: 40,
        totalFats: 15,
        foods: [
          { name: 'Baked Salmon', amount: '150g', calories: 280, protein: 39, carbs: 0, fats: 13, recipe: 'Season with dill, lemon, and olive oil. Bake at 400°F for 15-18 minutes.' },
          { name: 'Sweet Potato', amount: '150g', calories: 130, protein: 3, carbs: 30, fats: 0 },
          { name: 'Mixed Green Salad', amount: '150g', calories: 25, protein: 2, carbs: 4, fats: 0 },
          { name: 'Balsamic Vinaigrette', amount: '1 tbsp (15ml)', calories: 45, protein: 0, carbs: 4, fats: 3 },
        ],
      },
    ],
  },
  // Muscle Gain Plan
  {
    name: 'Muscle Builder Diet Plan',
    description: 'High-calorie, protein-rich diet designed to support muscle hypertrophy and recovery.',
    goal: 'muscle_gain',
    dailyCalories: 3200,
    macros: { protein: 30, carbs: 45, fats: 25 },
    tags: ['muscle gain', 'bulking', 'high calorie', 'high protein'],
    difficulty: 'moderate',
    duration: 16,
    isPublic: true,
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500',
    meals: [
      {
        name: 'Breakfast',
        time: '7:00 AM',
        totalCalories: 700,
        totalProtein: 45,
        totalCarbs: 80,
        totalFats: 20,
        foods: [
          { name: 'Oatmeal', amount: '100g dry', calories: 380, protein: 13, carbs: 66, fats: 7, recipe: 'Cook with whole milk, add banana and honey for extra calories.' },
          { name: 'Whole Eggs', amount: '3 eggs', calories: 210, protein: 18, carbs: 1, fats: 15 },
          { name: 'Banana', amount: '1 large (136g)', calories: 121, protein: 1, carbs: 31, fats: 0 },
          { name: 'Whole Milk', amount: '200ml', calories: 122, protein: 6, carbs: 9, fats: 7 },
        ],
      },
      {
        name: 'Mid-Morning Snack',
        time: '10:00 AM',
        totalCalories: 450,
        totalProtein: 35,
        totalCarbs: 45,
        totalFats: 12,
        foods: [
          { name: 'Mass Gainer Shake', amount: '1 serving (100g)', calories: 380, protein: 30, carbs: 50, fats: 8, recipe: 'Mix with whole milk for additional calories and protein.' },
          { name: 'Peanut Butter', amount: '2 tbsp (32g)', calories: 190, protein: 8, carbs: 6, fats: 16 },
        ],
      },
      {
        name: 'Lunch',
        time: '1:00 PM',
        totalCalories: 900,
        totalProtein: 60,
        totalCarbs: 100,
        totalFats: 25,
        foods: [
          { name: 'Ground Beef (lean)', amount: '200g', calories: 440, protein: 46, carbs: 0, fats: 28, recipe: 'Season with garlic, onion, and mixed spices. Cook in olive oil.' },
          { name: 'White Rice', amount: '250g cooked', calories: 325, protein: 6, carbs: 71, fats: 1 },
          { name: 'Mixed Vegetables', amount: '200g', calories: 80, protein: 5, carbs: 18, fats: 0 },
          { name: 'Avocado', amount: '50g', calories: 80, protein: 1, carbs: 4, fats: 7 },
        ],
      },
      {
        name: 'Pre-Workout Snack',
        time: '4:00 PM',
        totalCalories: 400,
        totalProtein: 20,
        totalCarbs: 60,
        totalFats: 8,
        foods: [
          { name: 'Whole Wheat Pasta', amount: '80g dry', calories: 280, protein: 10, carbs: 56, fats: 2 },
          { name: 'Tuna Can', amount: '1 can (140g)', calories: 165, protein: 33, carbs: 0, fats: 3 },
        ],
      },
      {
        name: 'Post-Workout & Dinner',
        time: '7:30 PM',
        totalCalories: 750,
        totalProtein: 55,
        totalCarbs: 70,
        totalFats: 20,
        foods: [
          { name: 'Chicken Breast', amount: '250g', calories: 385, protein: 72, carbs: 0, fats: 8 },
          { name: 'Sweet Potato', amount: '200g', calories: 172, protein: 4, carbs: 40, fats: 0 },
          { name: 'Broccoli & Asparagus', amount: '200g', calories: 70, protein: 7, carbs: 12, fats: 0 },
          { name: 'Olive Oil', amount: '1 tbsp (15ml)', calories: 119, protein: 0, carbs: 0, fats: 14 },
        ],
      },
    ],
  },
  // Maintenance Plan
  {
    name: 'Balanced Maintenance Plan',
    description: 'A well-balanced, sustainable diet to maintain your current weight and support overall health.',
    goal: 'maintenance',
    dailyCalories: 2400,
    macros: { protein: 25, carbs: 50, fats: 25 },
    tags: ['maintenance', 'balanced', 'sustainable', 'healthy'],
    difficulty: 'easy',
    duration: 0,
    isPublic: true,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
    meals: [
      {
        name: 'Breakfast',
        time: '7:30 AM',
        totalCalories: 500,
        totalProtein: 25,
        totalCarbs: 65,
        totalFats: 15,
        foods: [
          { name: 'Whole Grain Cereal', amount: '60g', calories: 220, protein: 6, carbs: 46, fats: 2 },
          { name: 'Low-Fat Milk', amount: '250ml', calories: 110, protein: 9, carbs: 12, fats: 3 },
          { name: 'Orange Juice', amount: '200ml', calories: 88, protein: 1, carbs: 21, fats: 0 },
          { name: 'Scrambled Eggs', amount: '2 eggs', calories: 182, protein: 12, carbs: 1, fats: 14 },
        ],
      },
      {
        name: 'Lunch',
        time: '12:30 PM',
        totalCalories: 700,
        totalProtein: 35,
        totalCarbs: 85,
        totalFats: 20,
        foods: [
          { name: 'Turkey Sandwich', amount: '1 sandwich', calories: 380, protein: 28, carbs: 45, fats: 10, recipe: 'Whole grain bread, turkey breast, lettuce, tomato, mustard.' },
          { name: 'Mixed Fruit Salad', amount: '150g', calories: 90, protein: 1, carbs: 23, fats: 0 },
          { name: 'Low-fat Yogurt', amount: '150g', calories: 100, protein: 8, carbs: 15, fats: 2 },
          { name: 'Sparkling Water', amount: '330ml', calories: 0, protein: 0, carbs: 0, fats: 0 },
        ],
      },
      {
        name: 'Afternoon Snack',
        time: '3:30 PM',
        totalCalories: 300,
        totalProtein: 10,
        totalCarbs: 40,
        totalFats: 12,
        foods: [
          { name: 'Hummus', amount: '60g', calories: 140, protein: 5, carbs: 12, fats: 8 },
          { name: 'Whole Grain Crackers', amount: '30g', calories: 120, protein: 3, carbs: 22, fats: 3 },
          { name: 'Carrot & Celery Sticks', amount: '100g', calories: 40, protein: 1, carbs: 9, fats: 0 },
        ],
      },
      {
        name: 'Dinner',
        time: '7:00 PM',
        totalCalories: 700,
        totalProtein: 35,
        totalCarbs: 70,
        totalFats: 25,
        foods: [
          { name: 'Baked Chicken Thighs', amount: '200g', calories: 310, protein: 40, carbs: 0, fats: 16, recipe: 'Season with herbs de Provence and olive oil. Bake at 375°F for 35-40 minutes.' },
          { name: 'Roasted Vegetables', amount: '250g', calories: 150, protein: 5, carbs: 28, fats: 4 },
          { name: 'Quinoa', amount: '100g cooked', calories: 120, protein: 4, carbs: 21, fats: 2 },
          { name: 'Olive Oil', amount: '1 tbsp', calories: 119, protein: 0, carbs: 0, fats: 14 },
        ],
      },
    ],
  },
];

// Main seeding function
const seedDatabase = async () => {
  try {
    await connectDatabase();

    // Clear existing data
    await Workout.deleteMany({});
    await Diet.deleteMany({});
    console.log('🗑️  Cleared existing workout and diet data');

    // Insert sample workouts
    const insertedWorkouts = await Workout.insertMany(sampleWorkouts);
    console.log(`✅ Inserted ${insertedWorkouts.length} workouts`);

    // Insert sample diet plans
    const insertedDiets = await Diet.insertMany(sampleDiets);
    console.log(`✅ Inserted ${insertedDiets.length} diet plans`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('You can now start the server and use the gym website.');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
